version: "3.9"

services:
  ticket-frontend:
    image: wikiarlnm/saffnco_ticket_frontend_app:latest
    container_name: ticket-frontend
    ports:
      - "3000:80"
    restart: always
    networks:
      - ticketing

networks:
  ticketing:
    driver: bridge
