version: "3.9"

services:
  ticketing-frontend:
    container_name: ticketing-frontend
    image: wikiarlnm/saffnco_ticket_frontend_app:latest
    pull_policy: always
    ports:
      - "3000:80"
    privileged: true
    restart: unless-stopped
    networks:
      - default
