version: "3.9"

services:
  ticketing-backend:
    container_name: ticketing-backend
    image: wikiarlnm/saffnco_ticket_backend_app:latest
    pull_policy: always
    ports:
      - "5000:80"
    volumes:
      - /DATA/AppData/ticketing/backend/.env:/var/www/html/.env
      - /DATA/AppData/ticketing/backend/storage:/var/www/html/storage
    privileged: true
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
