version: "3.8"

services:
  app:
    image: wikiarlnm/saffnco_ticket_backend_app:latest
    container_name: ticketing-backend
    ports:
      - "5000:80"
    volumes:
      - /DATA/AppData/ticketing/backend:/var/www/html
    restart: always
    networks:
      - ticketing

networks:
  ticketing:
    driver: bridge
