name: Build and Deploy

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: wikiarlnm/saffnco_ticket_backend_app:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: wikiarlnm/saffnco_ticket_frontend_app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: BACKEND_ENV
          script: |
            set -e
            export PATH=$PATH:/usr/local/bin
          
            echo "Create networks if not exist..."
            docker network create ticketing-backend-net || true
            docker network create ticketing-frontend-net || true
          
            echo "Deploying Backend..."
            docker pull wikiarlnm/saffnco_ticket_backend_app:latest
            docker stop ticketing-backend || true
            docker rm ticketing-backend || true
          
            echo "$BACKEND_ENV" > backend.tmp.env
          
            docker run -d \
              --name ticketing-backend \
              --restart always \
              --network ticketing-backend-net \
              -p 5000:80 \
              --cpu-shares 1024 \
              --memory 8G \
              --env-file backend.tmp.env \
              wikiarlnm/saffnco_ticket_backend_app:latest
          
            # connect backend to frontend network (optional but recommended)
            docker network connect ticketing-frontend-net ticketing-backend
          
            rm backend.tmp.env
          
            echo "Deploying Frontend..."
            docker pull wikiarlnm/saffnco_ticket_frontend_app:latest
            docker stop ticketing-frontend || true
            docker rm ticketing-frontend || true
          
            docker run -d \
              --name ticketing-frontend \
              --restart always \
              --network ticketing-frontend-net \
              -p 3000:80 \
              --cpu-shares 1024 \
              --memory 8G \
              wikiarlnm/saffnco_ticket_frontend_app:latest
          
            docker image prune -f
